export const FCC_OFFICIAL_SNAPSHOT = {
  "capturedAt": "2026-09-17T23:23:36.237Z",
  "source": "FCC Equipment Authorization System getFCCIDList",
  "sourceUrl": "https://apps.fcc.gov/OETLabServices/getFCCIDList",
  "scopes": [
    {
      "scope": "KWC",
      "granteeName": "Sonova USA Inc.",
      "registryDatasetId": "3b3k-34jp"
    },
    {
      "scope": "2A3UL",
      "granteeName": "Sonova Consumer Hearing GmbH",
      "registryDatasetId": null
    }
  ],
  "records": [
    {
      "FCCId": "KWC-ARNEM",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/02/2024",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-ARNESP",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/02/2024",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-BIO",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "11/27/2019",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-BPR",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/14/2021",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-BPZ",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/14/2021",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-BSP",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "12/04/2019",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-BSR",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/06/2019",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-BST",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "05/30/2019",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-BTD1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/20/2017",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-BTER",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/07/2017",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-BTEVSP",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/25/2016",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-BTEVUP",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/01/2016",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-CCG",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/26/2021",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-CCL",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/28/2022",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-CLICKNTALK",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/17/2009",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-COMPILOT1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "10/13/2011",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-COMPILOT11",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/11/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-COMPILOT2",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/07/2014",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-CONDOR",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Change in Identification",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "05/05/2009",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-CPAIR2",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "09/17/2014",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-DSF5K",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/21/2010",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-DSFX",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "05/01/2012",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-EC1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/23/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-EC2",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/24/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-ERF",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/11/2026",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-HGO",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "10/13/2020",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-HUB",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "05/15/2012",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-ICOM1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "05/27/2008",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-ICUBE1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/29/2008",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-ICUBE2",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/25/2014",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-IND",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/07/2020",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-INR",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/07/2020",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-IRF",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/24/2024",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-IRP",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/24/2024",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-ITEV10",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/21/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-ITEV10O",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/21/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-ITEV13",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "09/02/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-LDR",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Class II Permissive Change",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/13/2019",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-LDR",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "11/14/2018",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-LDZ",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "11/14/2018",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-MRP",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/22/2020",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-MYPILOT1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/29/2008",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-MZP",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/22/2020",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-NLCROS",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/28/2017",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-PILOTONE1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "05/27/2010",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-PILOTONE1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/03/2010",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-PILOTONE2",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/24/2014",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-PRF",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "05/27/2022",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-PRL",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/13/2021",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-RC1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Class II Permissive Change",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/11/2022",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-RC1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "05/29/2019",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-RICR",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/31/2016",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-RX24",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/18/2022",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-SLR",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/07/2022",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-TVCONNECTOR",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/19/2017",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-TVCONNECTV2",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "10/22/2018",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-TVLINK2",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "10/17/2011",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-TVLINKII",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Class II Permissive Change",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "11/03/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-TVLINKII",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "10/09/2014",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-TWE21",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/13/2022",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-TWE21EB",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/13/2022",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-TX23RCV1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/24/2016",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-TX23V1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/24/2016",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-TX29V1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/20/2018",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-VTI",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "12/27/2024",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-VTJ",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "12/27/2024",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-VTP",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/18/2022",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WFT1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/10/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSBTE",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/08/2008",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSBTE1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/21/2010",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSBTE1U",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/01/2011",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSBTEM",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/23/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSBTEP",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/23/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSBTESP",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/23/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSITE",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/08/2008",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSITE1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/21/2010",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSRIC1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "09/18/2014",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSRIC2",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "09/18/2014",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSRIC3",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "09/18/2014",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSRIC4",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "09/18/2014",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSSAN",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/07/2009",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSSAN1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/21/2010",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSSANQ",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "10/17/2012",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC-WHSSANT",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/22/2013",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC001R",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "09/22/1993",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC001T",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "09/22/1993",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC002R",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/13/1997",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC002T",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/14/1997",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC003R",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/13/1997",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWC004T",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/10/1998",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCAC",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/02/2010",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCACC04",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/02/2018",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCBWRXD",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/30/2014",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCCAMPUS",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "11/08/2001",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCCTX",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/08/2004",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCDMBASE",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/22/2016",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCDME",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/27/2016",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCDRX",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "05/29/2013",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCMYLINKD",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/15/2013",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCNCC",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/25/2019",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCPROFILO",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "05/30/2007",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCR20",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/03/2017",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCR21",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "05/19/2017",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCRCI",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "12/01/2005",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCRF",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/04/2014",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCRX23",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/29/2021",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCSE",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/05/2020",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTELCOM",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/24/2001",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTVLINK1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/11/2010",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX10",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/25/2009",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX10",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "07/01/2009",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX14",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/24/2012",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX15",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "02/02/2012",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX17",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "10/22/2013",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX17-1V1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/09/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX18",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "10/22/2013",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX18-1V1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/15/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX19",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/26/2016",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX20",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/26/2016",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX21",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/26/2016",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX22",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/21/2015",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX26",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/01/2018",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX27",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/18/2018",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX28V1",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "03/05/2019",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX300V",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "11/15/2006",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX32",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "08/22/2019",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX33",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/01/2021",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX6",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Class II Permissive Change",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "10/09/2009",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX6",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Class II Permissive Change",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "10/21/2009",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX6",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "11/19/2005",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX7",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Class II Permissive Change",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "01/09/2007",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX7",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Class II Permissive Change",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "10/26/2009",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX7",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "11/24/2005",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX9",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/10/2008",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX9",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/11/2008",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCTX9",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "04/18/2008",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "KWCWALLP",
      "address": "444 Commerce St. N/A",
      "applicationPurpose": "Original Equipment",
      "city": "Aurora",
      "country": "United States",
      "grantDate": "06/17/2004",
      "grantee": "Sonova USA Inc.",
      "state": "IL",
      "zipCode": "60504"
    },
    {
      "FCCId": "2A3ULACAEBT",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "06/15/2023",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULACPAEBT",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "08/30/2023",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULAOWS1",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "04/02/2026",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULATW1",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "11/22/2023",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULBTA1",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "09/19/2025",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULBTD600",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "07/20/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULBTD700",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "02/12/2025",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULBTT100",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/06/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULCONCPLUS1",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/06/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULCX200TW1L",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "11/03/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULCX200TW1R",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "11/04/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULCXPLUSTW1L",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "08/11/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULCXPLUSTW1R",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "08/10/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULHDBT",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "06/16/2025",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULHDR195",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/06/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULHDR275",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/03/2025",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULM4AEBT",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "07/11/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULM5AEBT",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "04/07/2026",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULMSPORT1",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "11/23/2023",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULMTW3L",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "03/24/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULMTW3R",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "03/24/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULMTW4",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "11/07/2023",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULMTW5",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "04/02/2026",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULOTW1",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "01/16/2025",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULRR2000",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/01/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULRR5000",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/06/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULRRFLEX",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/06/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULSB01",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/06/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULSB02M",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Class II Permissive Change",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "03/02/2023",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULSB02M",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "08/22/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULSEBT4",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/06/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULSW02",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "07/01/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULTR120W",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "07/01/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULTR195",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/06/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULTR2000",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/01/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULTR5000",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "12/01/2022",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULTVC2C",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "05/16/2023",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULTVC2EB",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Change in Identification",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "05/16/2023",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    },
    {
      "FCCId": "2A3ULTVC2TX",
      "address": "Im Heidkampe 9, 30659 Hannover",
      "applicationPurpose": "Original Equipment",
      "city": "Hannover",
      "country": "Germany",
      "grantDate": "04/06/2023",
      "grantee": "Sonova Consumer Hearing GmbH",
      "state": "N/A",
      "zipCode": "N/A"
    }
  ]
} as const;
